let users = [{ "id": 1, "name": "Blakeley", "email": "bstreets0@chronoengine.com", "gender": "Female", "contry": "Norway" },
{ "id": 2, "name": "Cordy", "email": "cearnshaw1@rediff.com", "gender": "Male", "contry": "France" },
{ "id": 3, "name": "Salome", "email": "samis2@google.pl", "gender": "Female", "contry": "Portugal" },
{ "id": 4, "name": "Klara", "email": "ktethcote3@sitemeter.com", "gender": "Female", "contry": "Dominican Republic" },
{ "id": 5, "name": "Ange", "email": "awalbrook4@jigsy.com", "gender": "Female", "contry": "Vietnam" },
{ "id": 6, "name": "Wells", "email": "wbeddis5@loc.gov", "gender": "Male", "contry": "Poland" },
{ "id": 7, "name": "Tallie", "email": "traden6@salon.com", "gender": "Male", "contry": "Finland" },
{ "id": 8, "name": "Lexy", "email": "lknapman7@yellowbook.com", "gender": "Female", "contry": "Philippines" },
{ "id": 9, "name": "Maxy", "email": "mveysey8@privacy.gov.au", "gender": "Female", "contry": "Samoa" },
{ "id": 10, "name": "Donny", "email": "dgodding9@sciencedirect.com", "gender": "Male", "contry": "China" },
{ "id": 11, "name": "Lawton", "email": "lkalinowskya@slideshare.net", "gender": "Male", "contry": "Indonesia" },
{ "id": 12, "name": "Farlee", "email": "fransonb@bravesites.com", "gender": "Male", "contry": "China" },
{ "id": 13, "name": "Keven", "email": "kpallisc@elpais.com", "gender": "Male", "contry": "Brazil" },
{ "id": 14, "name": "Joshia", "email": "jstirrupd@google.com.au", "gender": "Male", "contry": "Japan" },
{ "id": 15, "name": "Hastie", "email": "hmcnaee@dot.gov", "gender": "Male", "contry": "China" },
{ "id": 16, "name": "Jeddy", "email": "jjewettf@skyrock.com", "gender": "Male", "contry": "Portugal" },
{ "id": 17, "name": "Pinchas", "email": "pwitchg@webs.com", "gender": "Male", "contry": "Greece" },
{ "id": 18, "name": "Aubine", "email": "apetrinah@nsw.gov.au", "gender": "Female", "contry": "China" },
{ "id": 19, "name": "Shaylah", "email": "schrstinei@google.nl", "gender": "Female", "contry": "Poland" },
{ "id": 20, "name": "Welby", "email": "wsaurinj@paginegialle.it", "gender": "Male", "contry": "Mexico" },
{ "id": 21, "name": "Leonora", "email": "lmailek@uiuc.edu", "gender": "Female", "contry": "China" },
{ "id": 22, "name": "Zachariah", "email": "zaggettl@tuttocitta.it", "gender": "Male", "contry": "Mexico" },
{ "id": 23, "name": "Lawrence", "email": "lcattelm@meetup.com", "gender": "Agender", "contry": "Serbia" },
{ "id": 24, "name": "Leonhard", "email": "lbrazeltonn@tiny.cc", "gender": "Male", "contry": "Poland" },
{ "id": 25, "name": "Carie", "email": "crommeo@state.tx.us", "gender": "Non-binary", "contry": "China" },
{ "id": 26, "name": "Padgett", "email": "pduffriep@hud.gov", "gender": "Genderfluid", "contry": "France" },
{ "id": 27, "name": "Erwin", "email": "ealdieq@over-blog.com", "gender": "Male", "contry": "Indonesia" },
{ "id": 28, "name": "Edy", "email": "ehospitalr@ucoz.com", "gender": "Female", "contry": "Philippines" },
{ "id": 29, "name": "Noah", "email": "nebbings@behance.net", "gender": "Male", "contry": "Samoa" },
{ "id": 30, "name": "Celinka", "email": "ccubint@linkedin.com", "gender": "Female", "contry": "France" },
{ "id": 31, "name": "Maurizio", "email": "msadgroveu@cnet.com", "gender": "Male", "contry": "Brazil" },
{ "id": 32, "name": "Kassey", "email": "ksweedv@wsj.com", "gender": "Female", "contry": "Poland" },
{ "id": 33, "name": "Amery", "email": "ajosskowitzw@creativecommons.org", "gender": "Male", "contry": "Philippines" },
{ "id": 34, "name": "Eolande", "email": "evanthoffx@toplist.cz", "gender": "Female", "contry": "Bosnia and Herzegovina" },
{ "id": 35, "name": "Armando", "email": "alanphiery@accuweather.com", "gender": "Male", "contry": "China" },
{ "id": 36, "name": "Rosanna", "email": "rtamplingz@howstuffworks.com", "gender": "Female", "contry": "Philippines" },
{ "id": 37, "name": "Vinnie", "email": "vnealy10@bbb.org", "gender": "Male", "contry": "Indonesia" },
{ "id": 38, "name": "Mathew", "email": "mbarney11@live.com", "gender": "Male", "contry": "Russia" },
{ "id": 39, "name": "Pernell", "email": "pcoode12@netlog.com", "gender": "Male", "contry": "Greece" },
{ "id": 40, "name": "Aubry", "email": "ayandle13@domainmarket.com", "gender": "Female", "contry": "Indonesia" },
{ "id": 41, "name": "Adriano", "email": "aajsik14@illinois.edu", "gender": "Male", "contry": "Indonesia" },
{ "id": 42, "name": "Harp", "email": "hilyinski15@bbb.org", "gender": "Male", "contry": "Nigeria" },
{ "id": 43, "name": "Goddard", "email": "gfroude16@hp.com", "gender": "Male", "contry": "Russia" },
{ "id": 44, "name": "Tobye", "email": "tsinnett17@spiegel.de", "gender": "Female", "contry": "Sweden" },
{ "id": 45, "name": "Holly-anne", "email": "hqueyos18@pcworld.com", "gender": "Female", "contry": "Philippines" },
{ "id": 46, "name": "Stefanie", "email": "sbragginton19@nyu.edu", "gender": "Female", "contry": "Indonesia" },
{ "id": 47, "name": "Barrie", "email": "bhaysham1a@friendfeed.com", "gender": "Male", "contry": "China" },
{ "id": 48, "name": "Elvin", "email": "etrappe1b@xrea.com", "gender": "Male", "contry": "China" },
{ "id": 49, "name": "Berny", "email": "bmorrallee1c@about.com", "gender": "Male", "contry": "United States" },
{ "id": 50, "name": "Kalli", "email": "kglazzard1d@arizona.edu", "gender": "Female", "contry": "Indonesia" },
{ "id": 51, "name": "Priscella", "email": "pjeffry1e@microsoft.com", "gender": "Female", "contry": "Cameroon" },
{ "id": 52, "name": "Kata", "email": "kkeegan1f@latimes.com", "gender": "Female", "contry": "Japan" },
{ "id": 53, "name": "Lock", "email": "llangridge1g@4shared.com", "gender": "Male", "contry": "Panama" },
{ "id": 54, "name": "Darrell", "email": "dkarlsson1h@plala.or.jp", "gender": "Male", "contry": "Palestinian Territory" },
{ "id": 55, "name": "Stan", "email": "skybbye1i@ebay.com", "gender": "Male", "contry": "Slovenia" },
{ "id": 56, "name": "Antone", "email": "apoveleye1j@com.com", "gender": "Male", "contry": "Japan" },
{ "id": 57, "name": "Bridget", "email": "bkeyzman1k@a8.net", "gender": "Female", "contry": "China" },
{ "id": 58, "name": "Colline", "email": "cshingles1l@moonfruit.com", "gender": "Female", "contry": "China" },
{ "id": 59, "name": "Giffer", "email": "gdurnin1m@disqus.com", "gender": "Male", "contry": "Argentina" },
{ "id": 60, "name": "Nyssa", "email": "nbebis1n@miitbeian.gov.cn", "gender": "Genderqueer", "contry": "Chad" },
{ "id": 61, "name": "Gian", "email": "ggerding1o@un.org", "gender": "Male", "contry": "Brazil" },
{ "id": 62, "name": "Ulberto", "email": "umcgrath1p@google.fr", "gender": "Non-binary", "contry": "Philippines" },
{ "id": 63, "name": "Lucy", "email": "lrennebach1q@unblog.fr", "gender": "Female", "contry": "Colombia" },
{ "id": 64, "name": "Filippo", "email": "fvongrollmann1r@youtube.com", "gender": "Male", "contry": "Colombia" },
{ "id": 65, "name": "Hasty", "email": "hcapponer1s@bandcamp.com", "gender": "Male", "contry": "China" },
{ "id": 66, "name": "Jareb", "email": "jpenniell1t@purevolume.com", "gender": "Bigender", "contry": "Indonesia" },
{ "id": 67, "name": "Brina", "email": "bsimoneau1u@nationalgeographic.com", "gender": "Female", "contry": "Spain" },
{ "id": 68, "name": "Thornton", "email": "tanthill1v@wsj.com", "gender": "Male", "contry": "Russia" },
{ "id": 69, "name": "Cobbie", "email": "cblake1w@w3.org", "gender": "Male", "contry": "Russia" },
{ "id": 70, "name": "Waldo", "email": "wkerrich1x@businessinsider.com", "gender": "Genderfluid", "contry": "Portugal" },
{ "id": 71, "name": "Matthaeus", "email": "mmarkussen1y@oaic.gov.au", "gender": "Male", "contry": "France" },
{ "id": 72, "name": "Janessa", "email": "jjenno1z@soundcloud.com", "gender": "Genderfluid", "contry": "China" },
{ "id": 73, "name": "Janice", "email": "jfolkerts20@over-blog.com", "gender": "Female", "contry": "Finland" },
{ "id": 74, "name": "Lee", "email": "llaurence21@hc360.com", "gender": "Male", "contry": "Cameroon" },
{ "id": 75, "name": "Lamond", "email": "llangton22@arizona.edu", "gender": "Male", "contry": "Kenya" },
{ "id": 76, "name": "Lindsy", "email": "lfairest23@amazon.de", "gender": "Female", "contry": "Indonesia" },
{ "id": 77, "name": "Orion", "email": "ohucklesby24@accuweather.com", "gender": "Male", "contry": "China" },
{ "id": 78, "name": "Kristin", "email": "kumpleby25@networkadvertising.org", "gender": "Female", "contry": "Slovenia" },
{ "id": 79, "name": "Jacobo", "email": "jdavana26@wikia.com", "gender": "Polygender", "contry": "Canada" },
{ "id": 80, "name": "Fleurette", "email": "fharbisher27@dyndns.org", "gender": "Female", "contry": "Russia" },
{ "id": 81, "name": "Chariot", "email": "cpittoli28@aboutads.info", "gender": "Male", "contry": "France" },
{ "id": 82, "name": "Sky", "email": "scurrey29@usgs.gov", "gender": "Male", "contry": "China" },
{ "id": 83, "name": "Hewet", "email": "hcooke2a@senate.gov", "gender": "Male", "contry": "China" },
{ "id": 84, "name": "Cobbie", "email": "cminghi2b@apache.org", "gender": "Male", "contry": "Pakistan" },
{ "id": 85, "name": "Leora", "email": "lhattigan2c@nydailynews.com", "gender": "Female", "contry": "China" },
{ "id": 86, "name": "Yorgos", "email": "yselesnick2d@mashable.com", "gender": "Genderfluid", "contry": "Indonesia" },
{ "id": 87, "name": "Hubey", "email": "hchessor2e@china.com.cn", "gender": "Male", "contry": "Brazil" },
{ "id": 88, "name": "Leland", "email": "lfoxwell2f@trellian.com", "gender": "Male", "contry": "Ghana" },
{ "id": 89, "name": "Sharia", "email": "spavelin2g@spotify.com", "gender": "Female", "contry": "Ireland" },
{ "id": 90, "name": "Cale", "email": "cargyle2h@nationalgeographic.com", "gender": "Male", "contry": "Canada" },
{ "id": 91, "name": "Kermit", "email": "kballam2i@qq.com", "gender": "Male", "contry": "Canada" },
{ "id": 92, "name": "Nigel", "email": "nboobyer2j@amazon.com", "gender": "Male", "contry": "Portugal" },
{ "id": 93, "name": "Porty", "email": "psiddens2k@weibo.com", "gender": "Male", "contry": "China" },
{ "id": 94, "name": "Jojo", "email": "jtrayford2l@hugedomains.com", "gender": "Bigender", "contry": "China" },
{ "id": 95, "name": "Ivett", "email": "idibartolomeo2m@netlog.com", "gender": "Female", "contry": "Brazil" },
{ "id": 96, "name": "Wang", "email": "wguerri2n@prlog.org", "gender": "Male", "contry": "Greece" },
{ "id": 97, "name": "Alice", "email": "ajeves2o@slate.com", "gender": "Female", "contry": "Nigeria" },
{ "id": 98, "name": "Bartholomeo", "email": "bgehringer2p@lulu.com", "gender": "Male", "contry": "Colombia" },
{ "id": 99, "name": "Genny", "email": "gyouhill2q@pinterest.com", "gender": "Female", "contry": "Poland" },
{ "id": 100, "name": "Ricard", "email": "rdanzey2r@house.gov", "gender": "Male", "contry": "Norway" },
{ "id": 101, "name": "Damon", "email": "dkirkpatrick2s@vkontakte.ru", "gender": "Male", "contry": "Philippines" },
{ "id": 102, "name": "Tiffy", "email": "tambler2t@chronoengine.com", "gender": "Female", "contry": "Portugal" }]


function displayUserData() {

    let rows = ""
    for (user of users) {
        rows += `<tr>
                            <td> ${user.id}</td>
                            <td> ${user.name}</td>
                            <td> ${user.email}</td>
                            <td> ${user.gender.toUpperCase()}</td>
                            <td> ${user.contry}</td>
                              <td> ${user.email}</td>
                        </tr>`
    }
    document.getElementById('abc').innerHTML = rows
}